### ISSUE TITLE
Test functions

### ISSUE THREAD

**Issue by dejmail** [dejmail/begrepptjanst#7]
We need test functions to make sure that when we alter a feature in CSS/JS/HTML/Django that the rest of the functions distributed across the code are still able to function. That way we stop being reliant on Ctrl-Shift-R and going through each of the forms manually. It will drastically improve our output and really ease troubleshooting and debugging.

**Comment by trolibol** [comment]
When a Term is requested it will be filled within the begrepplist. This could be problematic since we dont have any verification that the ppl who request terms are valid. My suggestion is to set newly requested terms to "hidden" untill the backoffice have had time to verify the concepts. So we dont get alot of post from bots and immature teenagers.
